# My first cool idea {#bay-area-rent-price-predictor}

#### Keywords

bubble, housing, home price, rent

## A beginning.

My wife and I just moved back to San Francisco Bay Area and have looked for a 2bd house or apartnment in Millbrae, Burlingame, and San Mateo. Price range for a 2bd house or apartment in these cities is from $2.7k to $4.0k per month which is a lot higher than a median price for a 2bd house or apartment in the USA. We have spent more than 30 hours respectively to search for available options without knowing whether houses or apartments we have found have the right price. As 90,000 people moved in from July 2014 to July 2015 to San Francisco Bay Area, we could have wasted 2.7M hours collectively. In this context, I’d like to prevent incoming residents in San Francisco Bay Area from wasting time by showing how likely a rent price would go up or down.

## A middle.
When you search for flights or hotels in Google, Kayak or in online travel sites, it is not difficult to see them indicating whether your options are best deals or not, or whether prices are expected to go up or not. Shouldn’t we have the same capability for rents? That’s why I introduce you the Bay Area Rent Price Predictor. Based on the historical data of house or apartment sales and rents in this area, the predictor should be able to identify upward or downward trends in terms of home prices and rents and to even suggest the dates when newcomers are encouraged to move in San Francisco Bay Area.

## An end.

When people considering a move from different cities look for a place to rent in San Francisco Bay Area, they would be able to make a quick and right decision (pass/visit/apply) since the rent price predictor shows whether a rent price is within a range and how likely the price goes up or down in a foreseeable future. As a result, they will save more than 2.7M hours and money collectively and find places at the right prices in San Francisco Bay Area.
