# My second cool idea {#smart-body-scanner}

#### Keywords

passenger-scanning, TSA, delay, airport

## I missed my flight.
I arrived at Hartsfield–Jackson Atlanta International Airport in Atlanta, GA one and a half hour before my flight back to San Francisco. Since it was a domestic flight, I naively thought I could make it, but I missed the flight. It took more than 1 hour to go through the security check at the airport.
Delays in the security check are mainly caused by additional manual checks when the body scanners beep alarms, but these alarms are false positive in most cases. According to FAA, more than 2.5M domestic/international passengers fly every day. If we can reduce the false positives, we would save lots of time wasted at the airports collectively.

## Dynamic threshold.
How many times have you seen a traveler being called out for an additional search after the body scanner and a TSA agent found nothing? It is believed that 9 out of 10 cases are false positives, and they are the biggest cause of delays in the security check. Smart Body Scanner is a software which can be easily applied to various body scanners used across different airports. Smart Body Scanner dynamically adjusts a threshold based on traveler's security check and travel history when his or her passport is scanned before the body scanner. It can be also trained based on the scanned images collected from other body scanners. For example, the body scanner would be less sensitive when those who have traveled a lot and have not been additionally screened come through it. However, the body scanner would become more sensitive for first-time travelers and those who have the records. Smart Body Scanner will dramatically decrease the false positives.   

## Never miss your flight.
No more long lines in the security check when you arrive at the airport for your next flight with Smart Body Scanner. As the body scanner only picks the potential threats with much lower false positives, TSA agents can pay more attention to them, and are not required to work overtime to help alleviate the long lines. In addition, the shorter lines in the security check would help save lots of time collectively for more than 2.5M passengers flying every day. While lowering false positives is the primary benefit from Smart Body Scanner, no one wants to see false negatives go into any flights. Therefore, Smart Body Scanner will randomly lower its threshold to prevent them. Smart Body Scanner will bring no more delays and missing flights with security at the airport.

Sources
 - https://www.faa.gov/air_traffic/by_the_numbers/
 - http://www.news9.com/story/22112531/product-causes-owasso-woman-to-test-positive-for-explosives-at-airport
 - http://www.cnn.com/travel/article/tsa-long-lines-us-airports/index.html
